"""
CLORA-SecBox Artifact Inspector & Quota Enforcer.
Validates output files against quotas, extension whitelists, and magic-byte signatures.
Prevents disk exhaustion and executable smuggling via renamed extensions.
SIH Problem Statement 26117 (MRPL)
"""

import hashlib
import os
from typing import Dict, List, Set

from pydantic import BaseModel, Field


class ArtifactInspectionResult(BaseModel):
    valid: bool
    approved_files: List[str] = Field(default_factory=list)
    artifact_hashes: Dict[str, str] = Field(default_factory=dict)
    total_size_bytes: int = 0
    violations: List[str] = Field(default_factory=list)


ALLOWED_EXTENSIONS: Set[str] = {
    ".png", ".jpg", ".jpeg", ".svg", ".csv", ".json", ".txt", ".parquet"
}

# Binary magic headers of forbidden executables / scripts
FORBIDDEN_MAGIC_PREFIXES: List[bytes] = [
    b"MZ",                # Windows PE executable / DLL
    b"\x7fELF",           # Linux ELF executable
    b"\xfe\xed\xfa\xce",   # Mach-O binary
    b"\xcf\xfa\xed\xfe",   # Mach-O 64-bit
    b"\xca\xfe\xba\xbe",   # Java class / universal binary
]


class ArtifactInspector:
    """Inspects files generated by sandbox execution before returning them to the agent or user."""

    def __init__(
        self,
        max_files: int = 5,
        max_total_size_mb: float = 10.0,
    ) -> None:
        self.max_files = max_files
        self.max_total_bytes = int(max_total_size_mb * 1024 * 1024)

    def inspect(self, output_files: List[str]) -> ArtifactInspectionResult:
        """Validates all generated artifact files in the output directory."""
        approved_files: List[str] = []
        artifact_hashes: Dict[str, str] = {}
        total_size = 0
        violations: List[str] = []

        # 1. Quota: Maximum file count
        if len(output_files) > self.max_files:
            violations.append(
                f"Artifact file count quota exceeded: generated {len(output_files)} files (maximum permitted: {self.max_files})"
            )

        for fpath in output_files:
            if not os.path.isfile(fpath):
                continue

            fname = os.path.basename(fpath)
            _, ext = os.path.splitext(fname)
            ext_lower = ext.lower()

            # 2. Whitelist: Allowed file extensions
            if ext_lower not in ALLOWED_EXTENSIONS:
                violations.append(f"Disallowed file extension '{ext}' on artifact '{fname}'.")
                continue

            # Check file size
            file_size = os.path.getsize(fpath)
            total_size += file_size

            # 3. Quota: Total size ceiling
            if total_size > self.max_total_bytes:
                violations.append(
                    f"Artifact total size quota exceeded: {total_size / (1024*1024):.2f}MB (maximum permitted: {self.max_total_bytes / (1024*1024):.1f}MB)."
                )
                break

            # 4. Magic-byte verification
            try:
                with open(fpath, "rb") as f:
                    header = f.read(32)

                # Reject executable headers regardless of file extension
                if any(header.startswith(sig) for sig in FORBIDDEN_MAGIC_PREFIXES):
                    violations.append(f"Malicious executable header detected inside artifact '{fname}'.")
                    continue

                # Specific verification per format
                if ext_lower == ".png" and not header.startswith(b"\x89PNG\r\n\x1a\n"):
                    violations.append(f"Corrupt or spoofed PNG magic header in artifact '{fname}'.")
                    continue
                elif ext_lower in (".jpg", ".jpeg") and not header.startswith(b"\xff\xd8\xff"):
                    violations.append(f"Corrupt or spoofed JPEG magic header in artifact '{fname}'.")
                    continue
                elif ext_lower in (".csv", ".json", ".txt"):
                    # Text formats must not contain null bytes
                    if b"\x00" in header:
                        violations.append(f"Binary null byte detected inside supposed text file '{fname}'.")
                        continue

                # 5. Compute SHA-256 fingerprint
                with open(fpath, "rb") as f:
                    file_sha = hashlib.sha256(f.read()).hexdigest()

                approved_files.append(fpath)
                artifact_hashes[fname] = file_sha

            except Exception as e:
                violations.append(f"Error reading artifact '{fname}': {str(e)}")

        is_valid = len(violations) == 0
        return ArtifactInspectionResult(
            valid=is_valid,
            approved_files=approved_files if is_valid else [],
            artifact_hashes=artifact_hashes if is_valid else {},
            total_size_bytes=total_size,
            violations=violations,
        )


default_artifact_inspector = ArtifactInspector()
